/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Devia
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     * @param pServicio
     */
    public GUIPrincipal() 
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAcciones = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAgregarMatricula = new javax.swing.JMenuItem();
        jMenuItemEliminarMatricula = new javax.swing.JMenuItem();
        jMenuItemModificarMatricula = new javax.swing.JMenuItem();
        jMenuItemBuscarMatricula = new javax.swing.JMenuItem();
        jMenuItemListarMatricula = new javax.swing.JMenuItem();
        jMenuGrafica = new javax.swing.JMenu();
        jMenuItemGrafica = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University");
        setName(""); // NOI18N

        jMenuArchivo.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuAcciones.setText("Estudiante");

        jMenuItemAgregar.setText("Agregar");
        jMenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemAgregar);

        jMenuItemEliminar.setText("Eliminar");
        jMenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemEliminar);

        jMenuItemModificar.setText("Modificar");
        jMenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemModificar);

        jMenuItemBuscar.setText("Buscar");
        jMenuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemBuscar);

        jMenuItemListar.setText("Listar");
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemListar);

        jMenuBar.add(jMenuAcciones);

        jMenu1.setText("Matricula");

        jMenuItemAgregarMatricula.setText("Agregar");
        jMenuItemAgregarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarMatricula);

        jMenuItemEliminarMatricula.setText("Eliminar");
        jMenuItemEliminarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEliminarMatricula);

        jMenuItemModificarMatricula.setText("Modificar");
        jMenuItemModificarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemModificarMatricula);

        jMenuItemBuscarMatricula.setText("Buscar");
        jMenuItemBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBuscarMatricula);

        jMenuItemListarMatricula.setText("Listar");
        jMenuItemListarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListarMatricula);

        jMenuBar.add(jMenu1);

        jMenuGrafica.setText("Varios");

        jMenuItemGrafica.setText("Grafica");
        jMenuItemGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGraficaActionPerformed(evt);
            }
        });
        jMenuGrafica.add(jMenuItemGrafica);

        jMenuBar.add(jMenuGrafica);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca De");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Aplicación desarrollada por:" + "\n" + "Cristian Devia 2220161013" + "\n" + "Juan Rubio 2220161023");
        
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarActionPerformed
        // TODO add your handling code here:
        
        GUIEliminar guiEliminar = new GUIEliminar();
        guiEliminar.setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarActionPerformed

    private void jMenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarActionPerformed
        // TODO add your handling code here:
        
        GUIAgregar guiAgregar = new GUIAgregar();
        guiAgregar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAgregarActionPerformed

    private void jMenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarActionPerformed
        // TODO add your handling code here:
        
        GUIModificar guiModificar = new GUIModificar();
        guiModificar.setVisible(true);
    }//GEN-LAST:event_jMenuItemModificarActionPerformed

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarActionPerformed
        // TODO add your handling code here:
        GUIBuscar guiBuscar = new GUIBuscar();
        guiBuscar.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarActionPerformed

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        // TODO add your handling code here:
        GUIListar guiListar = new GUIListar();
        guiListar.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    private void jMenuItemGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGraficaActionPerformed
        // TODO add your handling code here:
        
        GUIGrafica guiGrafica = new GUIGrafica();
        guiGrafica.setVisible(true);
    }//GEN-LAST:event_jMenuItemGraficaActionPerformed

    private void jMenuItemAgregarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarMatriculaActionPerformed
        // TODO add your handling code here:
        GUIAgregarMatricula gui = new GUIAgregarMatricula();
        gui.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAgregarMatriculaActionPerformed

    private void jMenuItemEliminarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarMatriculaActionPerformed
        // TODO add your handling code here:
        GUIEliminarMatricula gui = new GUIEliminarMatricula();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarMatriculaActionPerformed

    private void jMenuItemModificarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarMatriculaActionPerformed
        // TODO add your handling code here:
        GUIModificarMatricula gui = new GUIModificarMatricula();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemModificarMatriculaActionPerformed

    private void jMenuItemBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarMatriculaActionPerformed
        // TODO add your handling code here:
        GUIBuscarMatricula gui = new GUIBuscarMatricula();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarMatriculaActionPerformed

    private void jMenuItemListarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarMatriculaActionPerformed
        // TODO add your handling code here:
        GUIListarMatricula gui = new GUIListarMatricula();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuGrafica;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemAgregarMatricula;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuItemBuscarMatricula;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemEliminarMatricula;
    private javax.swing.JMenuItem jMenuItemGrafica;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemListarMatricula;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenuItem jMenuItemModificarMatricula;
    private javax.swing.JMenuItem jMenuItemSalir;
    // End of variables declaration//GEN-END:variables

}
